services:
  mysql:
    image: mysql:8.0
    container_name: uniplan-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: uniplan
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
